operators-view:
  path: /
  methods: GET
  controller: App\Controller\OperatorController::index

operators-list:
  path: /operador
  methods: GET
  controller: App\Controller\OperatorController::list

operators-create:
  path: /operador
  controller: App\Controller\OperatorController::create
  methods: POST

operators-update:
  path: /operador/{email}
  methods: PUT,PATCH
  controller: App\Controller\OperatorController::update